name: Run Playwright Tests and Deploy Report

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Clean previous report
      run: rm -rf playwright-report

    - name: Run Playwright tests
      run: npx playwright test --reporter=html

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
        publish_branch: gh-pages
        keep_files: true
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com